#GET http://localhost:3000/

# POST http://localhost:3000/api/auth/login
# Content-Type: application/json

# {
#   "email": "cb11@gmail.com",
#   "password": "staff123"
# }

GET http://localhost:3000/api/auth/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJjYjExQGdtYWlsLmNvbSIsInJvbGUiOjMsImlhdCI6MTczOTcwMTI5NSwiZXhwIjoxNzM5Nzg3Njk1fQ.9SDGI1-KERskdGJYUj1iLa1DrOfq7sXxeDzcZF-BnF4

#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1dHNhdm5wbjdAZ21haWwuY29tIiwicm9sZSI6MSwiaWF0IjoxNzM5Njk5MzIzLCJleHAiOjE3Mzk3ODU3MjN9._1oq0-4bAadS0khk8XA0ey1K4IzL7sE1A6geIW8paLo
#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJiczEyQGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTczOTY5OTkwOSwiZXhwIjoxNzM5Nzg2MzA5fQ.Uj0Ar1KCT-OWlKjLiDRjVpLTWRfZdTni1m03iWMjbZI
#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJjYjExQGdtYWlsLmNvbSIsInJvbGUiOjMsImlhdCI6MTczOTcwMDA3MywiZXhwIjoxNzM5Nzg2NDczfQ.dvZsF9LoZYaJ0zTPcZce3KDQT0_QFafySyMTYpwfftQ
####
GET http://localhost:3000/api/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbXBsb3llZUlEIjoiMDFlY2EyYTAtZGJiZC00Y2Q0LWFmYTAtNTcxOWUwNTRkNDZjIiwiRW1haWwiOiJ1dHNhdm5ldXBhbmUxMjNAZXhhbXBsZS5jb20iLCJSb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDEyMzI4NTIsImV4cCI6MTc0MTI0MDA1Mn0.qU-KcmHvzK6VQ_YFNHalrBD8SoyC5SoG6WZsG9FD5jM


####
POST http://localhost:3000/api/employees

#### 
POST http://localhost:3000/api/employees
Content-Type: application/json

{
  "firstName": "Utsav",
  "lastName": "Neupane",
  "email": "utsavneupane123@example.com",
  "phoneNumber": "1234567890",
  "employmentStatus": "active",
  "role": "admin",
  "password": "securepassword123"
}

####
POST http://localhost:3000/api/employees/login
Content-Type: application/json

{
  "Email": "utsavneupane123@example.com",
  "Password":"securepassword123"}
####
POST http://localhost:3000/api/roster/createShift
Content-Type: application/json

{
  "employeeId": "f36bcf40-35e7-4d26-98b8-ecba5298acd7",
  "officeId": "c28ff698-2a66-469b-a36e-8b164c456b3f",
  "startTime": "2025-03-11T09:00:00.000Z",
  "endTime": "2025-03-11T17:00:00.000Z"
}
####
GET http://localhost:3000/api/roster
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbXBsb3llZUlEIjoiZjM2YmNmNDAtMzVlNy00ZDI2LTk4YjgtZWNiYTUyOThhY2Q3IiwiRW1haWwiOiJ1dHNhdm5ldXBhbmUxMjNAZXhhbXBsZS5jb20iLCJSb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDE2NDg3NTAsImV4cCI6MTc0MTY1NTk1MH0.MBKDXiMac6Aa0DW3C3NZTVXoNObwkYLOu41xTP354pY