#GET http://localhost:3000/

# POST http://localhost:3000/api/auth/login
# Content-Type: application/json

# {
#   "email": "bs12@gmail.com",
#   "password": "employee123"
# }

PUT http://localhost:3000/api/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1dHNhdm5wbjdAZ21haWwuY29tIiwicm9sZSI6MSwiaWF0IjoxNzM5ODc0MDIyLCJleHAiOjE3Mzk5NjA0MjJ9.EltR2EjK5Dq4TMQF0uHJjjnM8pOpQMtki0VyPkyoAAw

{
  "employmentStatus": "inactive"
}


#staff : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJjYjExQGdtYWlsLmNvbSIsInJvbGUiOjMsImlhdCI6MTczOTg3Mzg0NiwiZXhwIjoxNzM5OTYwMjQ2fQ.Al_GvIP_pgWWsZ3Q3ySu2iElcVlWxtebhWrHuPa-5Bg
#manager: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1dHNhdm5wbjdAZ21haWwuY29tIiwicm9sZSI6MSwiaWF0IjoxNzM5ODc0MDIyLCJleHAiOjE3Mzk5NjA0MjJ9.EltR2EjK5Dq4TMQF0uHJjjnM8pOpQMtki0VyPkyoAAw
#admin: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJiczEyQGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTczOTg3NDExMiwiZXhwIjoxNzM5OTYwNTEyfQ.3foRJuEYF6pQnTMGHayyQt3nZlKcgFT9zcT1hDfCLss